apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30200
  selector:
    spark-app: jupyter
